#------------------------------------------------------------------------------
# File:   $HOME/config/alacritty/alacritty.toml
# Author: Petr Zemek <s3rvac@petrzemek.net>
#------------------------------------------------------------------------------

[colors]
draw_bold_text_with_bright_colors = true
primary = { foreground = "#b2b2b2", dim_foreground = "#656565", bright_foreground = "#ffffff", background = "#000000" }
normal = { black = "#000000", red = "#b21818", green = "#18b218", yellow = "#b26818", blue = "#1818b2", magenta = "#b218b2", cyan = "#18b2b2", white = "#b2b2b2" }
bright = { black = "#686868", red = "#ff5454", green = "#54ff54", yellow = "#ffff54", blue = "#5454ff", magenta = "#ff54ff", cyan = "#54ffff", white = "#ffffff" }
dim = { black = "#000000", red = "#980000", green = "#006500", yellow = "#655e00", blue = "#000065", magenta = "#650065", cyan = "#006565", white = "#656565" }

[font]
size = 11
bold = { family = "monospace", style = "Bold" }
bold_italic = { family = "monospace", style = "Bold Italic" }
italic = { family = "monospace", style = "Italic" }
normal = { family = "monospace", style = "Regular" }
# Use a negative y offset to match the offset used by Qt apps (e.g. Konsole,
# Yakuake, Neovim Qt) as I want both Alacritty and other Qt apps to look as
# similar as possible.
offset = { x = 0, y = -2 }

[keyboard]
bindings = [
	# Make Ctrl-+ (Ctrl-Shift-=) increase font size for me as the default key
	# binding does not work.
	# https://github.com/alacritty/alacritty/issues/6496
	{ key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
]

[mouse]
hide_when_typing = true

[selection]
# Automatically copy the selected text into the clipboard.
save_to_clipboard = true

[window]
decorations = "None"
startup_mode = "Maximized"
